# Generated by Django 5.2.8 on 2025-11-22 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mylist', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
