# Generated by Django 5.2.8 on 2025-11-22 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylist', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
