# Generated by Django 5.2.8 on 2025-11-22 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylist', '0005_alter_task_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
